name: love_keeper_fe
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path: ^1.8.3
  path_provider: ^2.1.0

  # 네트워크 및 관련 패키지 (http 버전을 dart_code_metrics와 호환되는 버전으로 낮춤)
  http: ^0.13.6
  table_calendar: ^3.0.8
  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  
  # 텍스트 자동 포맷 관련
  mask_text_input_formatter: ^2.3.0

  # 네비게이션
  go_router: ^13.2.0

  # 네트워크
  dio: ^5.4.0
  retrofit: ^4.1.0
  cached_network_image: ^3.3.1

  # 코드 생성 관련
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # 로컬 스토리지
  shared_preferences: ^2.2.2

  fpdart: ^1.1.1
  flutter_svg: ^2.0.9   # 강제 다운그레이드 (충돌 방지)
  flex_color_scheme: ^7.3.1
  image_picker: ^1.0.4

  # Social Login
  kakao_flutter_sdk_user: ^1.9.1+2
  flutter_naver_login: ^1.8.0
  sign_in_with_apple: ^5.0.0

  # Friebase
  firebase_core: ^3.3.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^5.13.0

  build_runner: ^2.4.12
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.3.10
  dart_code_metrics: ^5.7.6

  mockito: ^5.4.4

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_page/
    - assets/images/onboarding/
    - assets/images/main_page/
    - assets/images/storage_page/
    - assets/images/tab_bar/
    - assets/images/letter_page/
    - assets/images/my_page/
    - assets/images/Backup/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
