name: love_keeper
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
 
  # 네트워크 및 관련 패키지 (http 버전을 dart_code_metrics와 호환되는 버전으로 낮춤)
  http: ^0.13.6
  table_calendar: ^3.0.8
  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  
  # 텍스트 자동 포맷 관련
  mask_text_input_formatter: ^2.3.0

  # 네비게이션
  go_router: ^13.2.0

  # 네트워크
  dio: ^5.4.0
  retrofit: ^4.1.0

  # 코드 생성 관련
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # 로컬 스토리지
  shared_preferences: ^2.2.2

  fpdart: ^1.1.1
  flutter_svg: ^2.0.9   # 강제 다운그레이드 (충돌 방지)
  flex_color_scheme: ^7.3.1
  image_picker: ^1.0.4

  # Social Login
  flutter_naver_login: ^1.8.0
  sign_in_with_apple: ^5.0.0
  kakao_flutter_sdk: ^1.9.6

  # Firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  cached_network_image: ^3.3.1
  kakao_flutter_sdk_user: ^1.9.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.3.10
  dart_code_metrics: ^5.7.6

  mockito: ^5.4.4

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_page/
    - assets/images/onboarding/
    - assets/images/main_page/
    - assets/images/storage_page/
    - assets/images/tab_bar/
    - assets/images/letter_page/
    - assets/images/my_page/
    - assets/images/Backup/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
