// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnxnlfB6ujK9Ly-U6pHFMJ6kh4USVS2rI',
    appId: '1:755912864251:web:bde724052057ca7bf99b5e',
    messagingSenderId: '755912864251',
    projectId: 'lovekeeper-c832d',
    authDomain: 'lovekeeper-c832d.firebaseapp.com',
    storageBucket: 'lovekeeper-c832d.firebasestorage.app',
    measurementId: 'G-CRMG0QY9DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO6_tibxo4E1M7fNRygj3losp2wcl4yKU',
    appId: '1:755912864251:android:1f67de6f034930b8f99b5e',
    messagingSenderId: '755912864251',
    projectId: 'lovekeeper-c832d',
    storageBucket: 'lovekeeper-c832d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpoAv0Kg1wEGR3mRBkByw9rLtHg_jz82A',
    appId: '1:755912864251:ios:eec282fab19f3766f99b5e',
    messagingSenderId: '755912864251',
    projectId: 'lovekeeper-c832d',
    storageBucket: 'lovekeeper-c832d.firebasestorage.app',
    iosBundleId: 'com.example.loveKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpoAv0Kg1wEGR3mRBkByw9rLtHg_jz82A',
    appId: '1:755912864251:ios:eec282fab19f3766f99b5e',
    messagingSenderId: '755912864251',
    projectId: 'lovekeeper-c832d',
    storageBucket: 'lovekeeper-c832d.firebasestorage.app',
    iosBundleId: 'com.example.loveKeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnxnlfB6ujK9Ly-U6pHFMJ6kh4USVS2rI',
    appId: '1:755912864251:web:02d85e3d12a5de84f99b5e',
    messagingSenderId: '755912864251',
    projectId: 'lovekeeper-c832d',
    authDomain: 'lovekeeper-c832d.firebaseapp.com',
    storageBucket: 'lovekeeper-c832d.firebasestorage.app',
    measurementId: 'G-3PMMSY8Y7R',
  );
}
