// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9s3KYpsHZXxuhXuehtMTNqRrFTaV3sd4',
    appId: '1:377496628791:web:0b3a2a92bda924d4b7d9b2',
    messagingSenderId: '377496628791',
    projectId: 'love-keeper-b9bc9',
    authDomain: 'love-keeper-b9bc9.firebaseapp.com',
    storageBucket: 'love-keeper-b9bc9.firebasestorage.app',
    measurementId: 'G-S0R91W678K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqDBXU2oz__BD0REw0Z8w7mfASLCNE_J4',
    appId: '1:377496628791:android:bee4d914102ee6dfb7d9b2',
    messagingSenderId: '377496628791',
    projectId: 'love-keeper-b9bc9',
    storageBucket: 'love-keeper-b9bc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB70QDln2f9HfxQG0oxGABERlW_8Nr5kFI',
    appId: '1:377496628791:ios:58661096dc0c7e80b7d9b2',
    messagingSenderId: '377496628791',
    projectId: 'love-keeper-b9bc9',
    storageBucket: 'love-keeper-b9bc9.firebasestorage.app',
    iosBundleId: 'com.example.lovekeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB70QDln2f9HfxQG0oxGABERlW_8Nr5kFI',
    appId: '1:377496628791:ios:aa5610a3c5d25adab7d9b2',
    messagingSenderId: '377496628791',
    projectId: 'love-keeper-b9bc9',
    storageBucket: 'love-keeper-b9bc9.firebasestorage.app',
    iosBundleId: 'com.example.loveKeeperFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCirjpaOMp8Uk8JOUFVvG5-zJ5G7TaeYm8',
    appId: '1:377496628791:web:381f3a42329f80b9b7d9b2',
    messagingSenderId: '377496628791',
    projectId: 'love-keeper-b9bc9',
    authDomain: 'love-keeper-b9bc9.firebaseapp.com',
    storageBucket: 'love-keeper-b9bc9.firebasestorage.app',
    measurementId: 'G-XWQGPTG7T1',
  );
}
